In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [ ]:
dataset = pd.read_csv('Battery_RUL.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[1.00000000e+00 2.59530000e+03 1.15148850e+03 ... 5.46000100e+03
  6.75501000e+03 1.07778200e+04]
 [2.00000000e+00 7.40864000e+03 1.17251250e+03 ... 5.50899200e+03
  6.76202000e+03 1.05003500e+04]
 [3.00000000e+00 7.39376000e+03 1.11299200e+03 ... 5.50899300e+03
  6.76202000e+03 1.04203800e+04]
 ...
 [1.11000000e+03 7.69120000e+02 1.79357143e+02 ... 9.15513000e+02
  1.41231000e+03 6.63712000e+03]
 [1.11100000e+03 7.73880000e+02 1.62374667e+02 ... 5.39375000e+02
  1.14800000e+03 7.66062000e+03]
 [1.11200000e+03 6.77537270e+05 1.42740640e+05 ... 4.96800040e+04
  5.99830140e+05 5.99830140e+05]]


In [ ]:
print(y)

[1112 1111 1110 ...    2    1    0]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,:])
X[:,:] = imputer.transform(X[:,:])

In [ ]:
print(X)

[[1.00000000e+00 2.59530000e+03 1.15148850e+03 ... 5.46000100e+03
  6.75501000e+03 1.07778200e+04]
 [2.00000000e+00 7.40864000e+03 1.17251250e+03 ... 5.50899200e+03
  6.76202000e+03 1.05003500e+04]
 [3.00000000e+00 7.39376000e+03 1.11299200e+03 ... 5.50899300e+03
  6.76202000e+03 1.04203800e+04]
 ...
 [1.11000000e+03 7.69120000e+02 1.79357143e+02 ... 9.15513000e+02
  1.41231000e+03 6.63712000e+03]
 [1.11100000e+03 7.73880000e+02 1.62374667e+02 ... 5.39375000e+02
  1.14800000e+03 7.66062000e+03]
 [1.11200000e+03 6.77537270e+05 1.42740640e+05 ... 4.96800040e+04
  5.99830140e+05 5.99830140e+05]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[ 160.         2074.34        627.2        ... 4544.351
  5516.35       9225.02      ]
 [ 628.         1395.38        385.5        ... 2486.281
  3284.28       8145.72      ]
 [ 996.         1076.56        291.28571429 ... 1623.17014286
  2276.31       7448.5       ]
 ...
 [ 313.         1895.8         540.         ... 3953.951
  4904.35       8821.41      ]
 [ 238.         1968.06        652.         ... 4280.375
  5228.38       8619.94      ]
 [ 429.         1678.72        490.71428571 ... 3368.353
  4256.35       8430.34      ]]


In [ ]:
print(X_test)

[[ 679.         1320.          364.         ... 2276.375
  3068.38       7892.38      ]
 [ 214.         1962.59        644.8        ... 4298.359
  5228.36       8905.09      ]
 [ 536.         1568.59        462.         ... 2966.344
  3860.34       8692.09      ]
 ...
 [ 560.         1576.5         465.         ... 3020.313
  3896.31       8073.81      ]
 [ 934.         1005.03        274.406      ... 1158.7735
  1918.02       8303.88      ]
 [ 519.         1604.48        418.97142857 ... 3025.144
  3932.34       8383.17      ]]


In [ ]:
print(y_train)

[948 486 112 ... 795 875 685]


In [ ]:
print(y_test)

[429 900 572 ... 548 174 589]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])

In [ ]:
print(X_train)

[[-1.23092231 -0.07542495 -0.04332552 ...  0.08249108  0.00159731
  -0.0324276 ]
 [ 0.22345602 -0.09585647 -0.0587205  ... -0.13846097 -0.08657954
  -0.07290396]
 [ 1.36706975 -0.10545052 -0.06472144 ... -0.23112357 -0.1263989
  -0.0990514 ]
 ...
 [-0.75545247 -0.08079764 -0.04887969 ...  0.01910641 -0.02257945
  -0.04756395]
 [-0.98852592 -0.07862316 -0.0417459  ...  0.05415092 -0.0097788
  -0.05511956]
 [-0.39496553 -0.08733009 -0.05201892 ... -0.04376273 -0.04817838
  -0.06223002]]


In [ ]:
print(X_test)

[[ 0.38194597 -0.09812483 -0.06008993 ... -0.16099624 -0.09510856
  -0.08240482]
 [-1.06310943 -0.07878777 -0.0422045  ...  0.05608166 -0.00977959
  -0.04442575]
 [-0.06244741 -0.09064417 -0.05384786 ... -0.08692195 -0.06382256
  -0.05241376]
 ...
 [ 0.01213609 -0.09040614 -0.05365678 ... -0.0811279  -0.06240159
  -0.07560076]
 [ 1.1743957  -0.10760303 -0.06579658 ... -0.28098066 -0.14055298
  -0.06697258]
 [-0.11527739 -0.08956415 -0.05658855 ... -0.08060925 -0.06097824
  -0.06399901]]


In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=32, activation='relu'));

In [ ]:
ann.add(tf.keras.layers.Dense(units=32, activation='relu'));

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

In [ ]:
ann.compile(optimizer='adam',loss='mean_squared_error')

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
377/377 [==============================] - 2s 2ms/step - loss: 320309.9375
Epoch 2/100
377/377 [==============================] - 1s 2ms/step - loss: 36245.6367
Epoch 3/100
377/377 [==============================] - 1s 2ms/step - loss: 10080.0752
Epoch 4/100
377/377 [==============================] - 1s 3ms/step - loss: 4568.7559
Epoch 5/100
377/377 [==============================] - 1s 3ms/step - loss: 2365.6172
Epoch 6/100
377/377 [==============================] - 1s 2ms/step - loss: 1427.8475
Epoch 7/100
377/377 [==============================] - 1s 2ms/step - loss: 967.3732
Epoch 8/100
377/377 [==============================] - 1s 2ms/step - loss: 736.0888
Epoch 9/100
377/377 [==============================] - 1s 2ms/step - loss: 587.5240
Epoch 10/100
377/377 [==============================] - 1s 2ms/step - loss: 477.3941
Epoch 11/100
377/377 [==============================] - 1s 2ms/step - loss: 404.0801
Epoch 12/100
377/377 [==============================] - 1s 2ms/s

In [ ]:
y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))


95/95 [==============================] - 0s 3ms/step
[[431.31 429.  ]
 [894.   900.  ]
 [572.54 572.  ]
 ...
 [550.44 548.  ]
 [173.07 174.  ]
 [589.9  589.  ]]


In [ ]:
test_loss = ann.evaluate(X_test, y_test)
print(test_loss)

95/95 [==============================] - 1s 5ms/step - loss: 59.7803
59.780311584472656


In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(mse)

59.780311709795555


In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(r2)

0.9994329475631535


In [ ]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print(mae)

4.169437360098858
